apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftWebConsole
  creationTimestamp: '2019-05-26T14:16:36Z'
  generation: 2
  labels:
    app: zinkin
  name: zinkin
  namespace: zinpkin-app
  resourceVersion: '692538'
  selfLink: /apis/apps.openshift.io/v1/namespaces/cli-test/deploymentconfigs/zinkin
  uid: def14de2-7fc0-11e9-acbd-0a1d4167cb58
spec:
  replicas: 1
  selector:
    app: zinkin
    deploymentconfig: zinkin
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftWebConsole
      creationTimestamp: null
      labels:
        app: zinkin
        deploymentconfig: zinkin
    spec:
      containers:
        - image: >-
            docker-registry.default.svc:5000/cli-test/zinkin@sha256:47fa4ccfedfd355ebc6be106c3c810b83cb572ae43d3a52d09e34912b6a23783
          imagePullPolicy: Always
          name: zinkin
          ports:
            - containerPort: 9411
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - zinkin
        from:
          kind: ImageStreamTag
          name: 'zinkin:latest'
          namespace: cli-test
        lastTriggeredImage: >-
          docker-registry.default.svc:5000/cli-test/zinkin@sha256:47fa4ccfedfd355ebc6be106c3c810b83cb572ae43d3a52d09e34912b6a23783
      type: ImageChange
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: '2019-05-26T14:16:42Z'
      lastUpdateTime: '2019-05-26T14:16:42Z'
      message: Deployment config has minimum availability.
      status: 'True'
      type: Available
    - lastTransitionTime: '2019-05-26T14:16:43Z'
      lastUpdateTime: '2019-05-26T14:16:43Z'
      message: replication controller "zinkin-1" successfully rolled out
      reason: NewReplicationControllerAvailable
      status: 'True'
      type: Progressing
  details:
    causes:
      - type: ConfigChange
    message: config change
  latestVersion: 1
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  unavailableReplicas: 0
  updatedReplicas: 1
