apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: zinkin
    openshift.io/deployment-config.name: zinkin
  name: zinkin
  namespace: cli-test
  ownerReferences:
    - apiVersion: apps.openshift.io/v1
      blockOwnerDeletion: true
      controller: true
      kind: DeploymentConfig
      name: zinkin
  resourceVersion: '687818'
spec:
  replicas: 1
  selector:
    app: zinkin
    deployment: zinkin
    deploymentconfig: zinkin
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: zinkin
        deployment: zinkin
        deploymentconfig: zinkin
    spec:
      containers:
        - image: >-
            docker-registry.default.svc:5000/cli-test/zinkin@sha256:6d30546d202be5f1a48e9f2fc8c6a80556b6f412347cdc1d74bbd15dbded5023
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 9411
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 2
          name: zinkin
          ports:
            - containerPort: 9411
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  fullyLabeledReplicas: 1
  observedGeneration: 3
  readyReplicas: 1
  replicas: 1
